name: CRNN-env
channels:
  - comet_ml
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyter
  - matplotlib
  - python-dotenv
  - pyyaml
  - ruamel.yaml
  - tqdm
  - wandb
  - tensorflow
  - pandas
  # - pip
  # - pip:
  #     - tensorflow-text==2.11
